### ISSUE TITLE
Dream Town doesn't work

### ISSUE THREAD

**Issue by AokiOfMidnight** [LiEnby/TamaTown#6]
Hello, I tried to play Tamagotchi Friends Dream Town, but when I tried it, it only appears a white screen. I tried it multiple times but still nothing, it only appears to download the files, change the password and change the language at the bottom of the page. I also tried with v5, e-tamago and uratama, and them worked very well.
![imagen_2024-08-27_011037140](https://github.com/user-attachments/assets/58640170-672b-4f2d-881f-44f8178e8cfb)

**Comment by LiEnby** [comment]
your browser doesn't support Adobe Flash Player, (pretty much none of the major browsers do anymore..) 
and DreamTown does not work in the [ruffle flash emulator](https://github.com/ruffle-rs/ruffle/issues/17215#issuecomment-2241941788) yet.

trying it on something like IE with Flash ActiveX installed, it does work. 
![image](https://github.com/user-attachments/assets/79be39b7-e85f-4006-821e-2b6952bb8515)


see this page : https://famitama.xyz/flash.html about running it in the standalone flash player from adobe,
